/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Difficulty = IDL.Variant({
  'Beginner' : IDL.Null,
  'Advanced' : IDL.Null,
  'Intermediate' : IDL.Null,
});
export const Program = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'difficulty' : Difficulty,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isPopular' : IDL.Bool,
  'category' : IDL.Text,
});
export const Trainer = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'yearsExperience' : IDL.Nat,
  'name' : IDL.Text,
  'specialty' : IDL.Text,
  'certifications' : IDL.Vec(IDL.Text),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getPrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
  'getTrainers' : IDL.Func([], [IDL.Vec(Trainer)], ['query']),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Difficulty = IDL.Variant({
    'Beginner' : IDL.Null,
    'Advanced' : IDL.Null,
    'Intermediate' : IDL.Null,
  });
  const Program = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'difficulty' : Difficulty,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isPopular' : IDL.Bool,
    'category' : IDL.Text,
  });
  const Trainer = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'yearsExperience' : IDL.Nat,
    'name' : IDL.Text,
    'specialty' : IDL.Text,
    'certifications' : IDL.Vec(IDL.Text),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getPrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
    'getTrainers' : IDL.Func([], [IDL.Vec(Trainer)], ['query']),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };