/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export type Difficulty = { 'Beginner' : null } |
  { 'Advanced' : null } |
  { 'Intermediate' : null };
export interface Program {
  'id' : bigint,
  'duration' : bigint,
  'difficulty' : Difficulty,
  'name' : string,
  'description' : string,
  'isPopular' : boolean,
  'category' : string,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Time = bigint;
export interface Trainer {
  'id' : bigint,
  'bio' : string,
  'yearsExperience' : bigint,
  'name' : string,
  'specialty' : string,
  'certifications' : Array<string>,
}
export interface _SERVICE {
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getPrograms' : ActorMethod<[], Array<Program>>,
  'getTrainers' : ActorMethod<[], Array<Trainer>>,
  'submitContact' : ActorMethod<[string, string, string, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];